# Generated by Django 4.2.4 on 2025-06-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspirantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirante',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='aspirantes/pdf/'),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='aspirantes/imagenes/'),
        ),
        migrations.AlterField(
            model_name='aspirante',
            name='curso',
            field=models.CharField(choices=[('Full Stack', 'Full Stack'), ('Data Science', 'Data Science'), ('Machine Learning', 'Machine Learning'), ('DevOps', 'DevOps')], max_length=20),
        ),
    ]
