# Generated by Django 4.2.4 on 2025-06-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspirantes', '0002_aspirante_archivo_pdf_aspirante_imagen_perfil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirante',
            name='aceptado',
            field=models.BooleanField(default=False),
        ),
    ]
